name = "TEP"
uuid = "eb9f2fad-3fa0-4abb-839d-82a3b9cc9b30"
authors = ["Yure Rocha <yure.trs@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JobQueueMPI = "32d208e1-246e-420c-b6ff-18b71b410923"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
BenchmarkTools = "1.6.0"
CSV = "0.10.15"
DataFrames = "1.7.0"
Dates = "1.11.0"
Distributions = "0.25.118"
Gurobi = "1.6.0"
Ipopt = "1.7.3"
JSON = "0.21.4"
JobQueueMPI = "0.1.1"
JuMP = "1.24.0"
LinearAlgebra = "1.11.0"
MPI = "0.20.22"
MathOptInterface = "1.30.0"
OrderedCollections = "1.8.0"
PowerModels = "0.21.3"
Serialization = "1.11.0"
SparseArrays = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
